url: "3dcomputervision.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "3DVisLab" # the name of your site, e.g. ACME Corp.
description: "3D vision group at CSE@IITJ and CVIT@IIITH"
